-- ============================================================
-- SCAFFOLD OS – SYSTEM-CHECK v2: Migrationen vs. echte Datenbank
-- KOMMAFREIE VERSION: Kein Komma kann beim Einfuegen verloren
-- gehen. Jede Zeile im Block unten: tabelle.spalte.quelle
-- (leere Spalte = nur Tabellen-Existenz pruefen).
-- REIN LESEND. SQL Editor -> RUN. Laufzeit 1-2 Min normal.
-- ============================================================

with expected as (
  select split_part(zeile, '.', 1) as tabelle,
         nullif(split_part(zeile, '.', 2), '') as spalte,
         split_part(zeile, '.', 3) as quelle
  from string_to_table(
$$absences..kunden-schema
company_settings..kunden-schema
customer_contacts..phase-28-kunden-vervollstaendigen
customers..kunden-schema
delivery_note_counters..phase-37-lieferschein
delivery_notes..phase-37-lieferschein
drivers..kunden-schema
email_log..phase-20-email-log
employee_skills..kunden-schema
employees..kunden-schema
gps_tracking..kunden-schema
impact_events..kunden-schema
inventory..kunden-schema
inventory_transactions..kunden-schema
invoice_counters..kunden-schema
invoice_freigabe_override..phase-27-freigabe-pflicht
invoice_payments..phase-38-teilzahlungen
invoices..kunden-schema
ki_jobs..phase-65-ki-jobs
kolonnen..phase-55-kolonnen
lead_termine..lead-termine
profiles..kunden-schema
project_access_tokens..phase-33-fernannahme
project_assignments..phase-28-kunden-vervollstaendigen
project_events..phase-18-projekt-dokumentation
project_media..kunden-schema
project_versions..phase-25-versionierung
projects..kunden-schema
site_stock..kunden-schema
subcontractor_entries..migration-nachunternehmer
subcontractors..migration-nachunternehmer
subscriptions..phase-12-stripe-abo
taeglicher_einsatz..phase-54-wochenplanung
tenants..phase-10-tenants
time_entries..kunden-schema
tour_assignments..kunden-schema
tour_plans..kunden-schema
tour_stops..kunden-schema
tours..kunden-schema
transport_orders..kunden-schema
vehicles..kunden-schema
absences.approved_at.kunden-schema
absences.approved_by.kunden-schema
absences.certificate_uploaded.kunden-schema
absences.created_at.kunden-schema
absences.created_by.kunden-schema
absences.employee_id.kunden-schema
absences.end_date.kunden-schema
absences.id.kunden-schema
absences.reason.kunden-schema
absences.start_date.kunden-schema
absences.status.kunden-schema
absences.type.kunden-schema
absences.updated_at.kunden-schema
company_settings.bank_name.kunden-schema
company_settings.bic.kunden-schema
company_settings.calc_crane_day.migration-kalkulations-grundlagen
company_settings.calc_hourly_rate.migration-kalkulations-grundlagen
company_settings.calc_hours_per_sqm.migration-kalkulations-grundlagen
company_settings.calc_permit_high.migration-kalkulations-grundlagen
company_settings.calc_permit_low.migration-kalkulations-grundlagen
company_settings.calc_transport_min.migration-kalkulations-grundlagen
company_settings.calc_transport_per_kg.migration-kalkulations-grundlagen
company_settings.calc_trip_flat.migration-kalkulations-grundlagen
company_settings.city.kunden-schema
company_settings.company_name.kunden-schema
company_settings.created_at.kunden-schema
company_settings.depot_address.kunden-schema
company_settings.email.kunden-schema
company_settings.iban.kunden-schema
company_settings.id.kunden-schema
company_settings.mahnung_pauschale.phase-36-mahnung-zinsen
company_settings.mahnung_verzugszinssatz.phase-36-mahnung-zinsen
company_settings.phone.kunden-schema
company_settings.steuer_nr.kunden-schema
company_settings.street.kunden-schema
company_settings.updated_at.kunden-schema
company_settings.ust_id.kunden-schema
company_settings.website.kunden-schema
company_settings.zip.kunden-schema
customer_contacts.bezeichnung.phase-28-kunden-vervollstaendigen
customer_contacts.created_at.phase-28-kunden-vervollstaendigen
customer_contacts.customer_id.phase-28-kunden-vervollstaendigen
customer_contacts.email.phase-28-kunden-vervollstaendigen
customer_contacts.id.phase-28-kunden-vervollstaendigen
customer_contacts.is_primary.phase-28-kunden-vervollstaendigen
customer_contacts.name.phase-28-kunden-vervollstaendigen
customer_contacts.phone.phase-28-kunden-vervollstaendigen
customers.city.kunden-schema
customers.contact_person.kunden-schema
customers.created_at.kunden-schema
customers.email.kunden-schema
customers.id.kunden-schema
customers.is_active.kunden-schema
customers.name.kunden-schema
customers.notes.kunden-schema
customers.phone.kunden-schema
customers.street.kunden-schema
customers.updated_at.kunden-schema
customers.zip.kunden-schema
delivery_note_counters.last_number.phase-37-lieferschein
delivery_note_counters.year.phase-37-lieferschein
delivery_notes.company_snapshot.phase-37-lieferschein
delivery_notes.created_at.phase-37-lieferschein
delivery_notes.customer_address.phase-37-lieferschein
delivery_notes.customer_id.phase-37-lieferschein
delivery_notes.customer_name.phase-37-lieferschein
delivery_notes.id.phase-37-lieferschein
delivery_notes.ls_number.phase-37-lieferschein
delivery_notes.materials.phase-37-lieferschein
delivery_notes.notes.phase-37-lieferschein
delivery_notes.performed_date.phase-37-lieferschein
delivery_notes.project_id.phase-37-lieferschein
delivery_notes.signature_data_url.phase-37-lieferschein
delivery_notes.signed_by_name.phase-37-lieferschein
delivery_notes.type.phase-37-lieferschein
drivers.created_at.kunden-schema
drivers.current_vehicle_id.kunden-schema
drivers.employee_id.kunden-schema
drivers.id.kunden-schema
drivers.is_active.kunden-schema
drivers.license_class.kunden-schema
drivers.license_expires.kunden-schema
drivers.name.kunden-schema
drivers.phone.kunden-schema
drivers.profile_id.kunden-schema
drivers.status.kunden-schema
email_log.id.phase-20-email-log
email_log.invoice_number.phase-20-email-log
email_log.project_id.phase-20-email-log
email_log.resend_id.phase-20-email-log
email_log.sent_at.phase-20-email-log
email_log.subject.phase-20-email-log
email_log.to_email.phase-20-email-log
email_log.type.phase-20-email-log
employee_skills.certificate_number.kunden-schema
employee_skills.certified_until.kunden-schema
employee_skills.created_at.kunden-schema
employee_skills.employee_id.kunden-schema
employee_skills.id.kunden-schema
employee_skills.level.kunden-schema
employee_skills.skill_name.kunden-schema
employees.created_at.kunden-schema
employees.created_by.kunden-schema
employees.drivers_license.kunden-schema
employees.email.kunden-schema
employees.first_name.kunden-schema
employees.home_address.kunden-schema
employees.home_lat.kunden-schema
employees.home_lng.kunden-schema
employees.hourly_rate.kunden-schema
employees.id.kunden-schema
employees.kolonne_id.phase-55-kolonnen
employees.last_name.kunden-schema
employees.license_expires.kunden-schema
employees.notes.kunden-schema
employees.phone.kunden-schema
employees.role.kunden-schema
employees.status.kunden-schema
employees.updated_at.kunden-schema
employees.updated_by.kunden-schema
employees.user_id.kunden-schema
employees.weekly_hours.kunden-schema
gps_tracking.accuracy.kunden-schema
gps_tracking.battery_level.kunden-schema
gps_tracking.created_at.kunden-schema
gps_tracking.driver_id.kunden-schema
gps_tracking.heading.kunden-schema
gps_tracking.id.kunden-schema
gps_tracking.lat.kunden-schema
gps_tracking.lng.kunden-schema
gps_tracking.speed.kunden-schema
gps_tracking.vehicle_id.kunden-schema
impact_events.created_at.kunden-schema
impact_events.einheit.kunden-schema
impact_events.event.kunden-schema
impact_events.id.kunden-schema
impact_events.meta.kunden-schema
impact_events.wert.kunden-schema
inventory.barcode.kunden-schema
inventory.category.kunden-schema
inventory.created_at.kunden-schema
inventory.created_by.kunden-schema
inventory.description.kunden-schema
inventory.id.kunden-schema
inventory.is_active.kunden-schema
inventory.location_in_warehouse.kunden-schema
inventory.min_stock.kunden-schema
inventory.name.kunden-schema
inventory.quantity.kunden-schema
inventory.reorder_point.kunden-schema
inventory.sku.kunden-schema
inventory.supplier.kunden-schema
inventory.supplier_lead_time.kunden-schema
inventory.unit.kunden-schema
inventory.unit_price.kunden-schema
inventory.updated_at.kunden-schema
inventory.updated_by.kunden-schema
inventory.weight_kg.migration-kalkulations-grundlagen
inventory_transactions.created_at.kunden-schema
inventory_transactions.created_by.kunden-schema
inventory_transactions.id.kunden-schema
inventory_transactions.inventory_id.kunden-schema
inventory_transactions.project_id.kunden-schema
inventory_transactions.quantity.kunden-schema
inventory_transactions.reason.kunden-schema
inventory_transactions.reference_id.kunden-schema
inventory_transactions.reference_type.kunden-schema
inventory_transactions.type.kunden-schema
invoice_counters.last_number.kunden-schema
invoice_counters.prefix.phase-22-gutschrift
invoice_counters.year.kunden-schema
invoice_freigabe_override.admin_id.phase-27-freigabe-pflicht
invoice_freigabe_override.created_at.phase-27-freigabe-pflicht
invoice_freigabe_override.grund.phase-27-freigabe-pflicht
invoice_freigabe_override.id.phase-27-freigabe-pflicht
invoice_freigabe_override.invoice_id.phase-27-freigabe-pflicht
invoice_freigabe_override.project_id.phase-27-freigabe-pflicht
invoice_payments.amount.phase-38-teilzahlungen
invoice_payments.created_at.phase-38-teilzahlungen
invoice_payments.id.phase-38-teilzahlungen
invoice_payments.invoice_id.phase-38-teilzahlungen
invoice_payments.note.phase-38-teilzahlungen
invoice_payments.payment_date.phase-38-teilzahlungen
invoices.company_snapshot.kunden-schema
invoices.created_at.kunden-schema
invoices.customer_address.kunden-schema
invoices.customer_id.phase-34-kunde-projekt-verknuepfung
invoices.customer_name.kunden-schema
invoices.due_date.kunden-schema
invoices.gross_amount.kunden-schema
invoices.id.kunden-schema
invoices.invoice_date.kunden-schema
invoices.invoice_number.kunden-schema
invoices.invoice_type.kunden-schema
invoices.net_amount.kunden-schema
invoices.notes.kunden-schema
invoices.paid_amount.phase-38-teilzahlungen
invoices.positions.kunden-schema
invoices.project_id.kunden-schema
invoices.reference_invoice_number.phase-22-gutschrift
invoices.reminder_level.kunden-schema
invoices.status.kunden-schema
invoices.tax_amount.kunden-schema
invoices.tax_rate.kunden-schema
invoices.updated_at.kunden-schema
ki_jobs.error.phase-65-ki-jobs
ki_jobs.erstellt_am.phase-65-ki-jobs
ki_jobs.erstellt_von.phase-65-ki-jobs
ki_jobs.fertig_am.phase-65-ki-jobs
ki_jobs.gestartet_am.phase-65-ki-jobs
ki_jobs.id.phase-65-ki-jobs
ki_jobs.max_versuche.phase-65-ki-jobs
ki_jobs.model.phase-65-ki-jobs
ki_jobs.payload.phase-65-ki-jobs
ki_jobs.project_id.phase-65-ki-jobs
ki_jobs.result.phase-65-ki-jobs
ki_jobs.status.phase-65-ki-jobs
ki_jobs.type.phase-65-ki-jobs
ki_jobs.versuche.phase-65-ki-jobs
kolonnen.bauleiter_id.phase-55-kolonnen
kolonnen.created_at.phase-55-kolonnen
kolonnen.id.phase-55-kolonnen
kolonnen.name.phase-55-kolonnen
lead_termine.art.lead-termine
lead_termine.created_at.lead-termine
lead_termine.datum.lead-termine
lead_termine.email.lead-termine
lead_termine.firma.lead-termine
lead_termine.id.lead-termine
lead_termine.nachricht.lead-termine
lead_termine.name.lead-termine
lead_termine.telefon.lead-termine
lead_termine.uhrzeit.lead-termine
profiles.company.kunden-schema
profiles.created_at.kunden-schema
profiles.email.kunden-schema
profiles.full_name.kunden-schema
profiles.id.kunden-schema
profiles.role.kunden-schema
project_access_tokens.created_at.phase-33-fernannahme
project_access_tokens.id.phase-33-fernannahme
project_access_tokens.project_id.phase-33-fernannahme
project_access_tokens.token.phase-33-fernannahme
project_assignments.created_at.phase-28-kunden-vervollstaendigen
project_assignments.created_by.phase-28-kunden-vervollstaendigen
project_assignments.employee_id.phase-28-kunden-vervollstaendigen
project_assignments.id.phase-28-kunden-vervollstaendigen
project_assignments.project_id.phase-28-kunden-vervollstaendigen
project_assignments.rolle.phase-28-kunden-vervollstaendigen
project_events.created_at.phase-18-projekt-dokumentation
project_events.created_by.phase-18-projekt-dokumentation
project_events.employee_id.phase-18-projekt-dokumentation
project_events.id.phase-18-projekt-dokumentation
project_events.photos.phase-18-projekt-dokumentation
project_events.project_id.phase-18-projekt-dokumentation
project_events.status.phase-18-projekt-dokumentation
project_events.text_note.phase-18-projekt-dokumentation
project_events.tour_stop_id.phase-18-projekt-dokumentation
project_events.type.phase-18-projekt-dokumentation
project_events.updated_at.phase-18-projekt-dokumentation
project_media.created_at.kunden-schema
project_media.file_name.kunden-schema
project_media.file_type.kunden-schema
project_media.id.kunden-schema
project_media.metadata.kunden-schema
project_media.project_id.kunden-schema
project_media.session_id.kunden-schema
project_media.storage_path.kunden-schema
project_media.uploaded_by.kunden-schema
project_versions.adresse.phase-25-versionierung
project_versions.created_at.phase-25-versionierung
project_versions.created_by.phase-25-versionierung
project_versions.data.phase-25-versionierung
project_versions.id.phase-25-versionierung
project_versions.name.phase-25-versionierung
project_versions.note.phase-25-versionierung
project_versions.project_id.phase-25-versionierung
project_versions.version_number.phase-25-versionierung
projects.adresse.kunden-schema
projects.created_at.kunden-schema
projects.customer_id.phase-34-kunde-projekt-verknuepfung
projects.data.kunden-schema
projects.id.kunden-schema
projects.name.kunden-schema
projects.status.kunden-schema
projects.user_id.kunden-schema
site_stock.created_at.kunden-schema
site_stock.created_by.kunden-schema
site_stock.id.kunden-schema
site_stock.inventory_id.kunden-schema
site_stock.last_counted_at.kunden-schema
site_stock.min_stock.kunden-schema
site_stock.project_id.kunden-schema
site_stock.quantity.kunden-schema
site_stock.reserved_quantity.kunden-schema
site_stock.status.kunden-schema
site_stock.updated_at.kunden-schema
site_stock.updated_by.kunden-schema
subcontractor_entries.art.migration-nachunternehmer
subcontractor_entries.bemerkung.migration-nachunternehmer
subcontractor_entries.betrag.migration-nachunternehmer
subcontractor_entries.created_at.migration-nachunternehmer
subcontractor_entries.created_by.migration-nachunternehmer
subcontractor_entries.datum.migration-nachunternehmer
subcontractor_entries.einheitspreis.migration-nachunternehmer
subcontractor_entries.id.migration-nachunternehmer
subcontractor_entries.menge.migration-nachunternehmer
subcontractor_entries.project_id.migration-nachunternehmer
subcontractor_entries.project_name.migration-nachunternehmer
subcontractor_entries.status.migration-nachunternehmer
subcontractor_entries.stundenzettel.migration-nachunternehmer
subcontractor_entries.subcontractor_id.migration-nachunternehmer
subcontractors.anfahrt_pauschale.migration-nachunternehmer
subcontractors.ansprechpartner.migration-nachunternehmer
subcontractors.city.migration-nachunternehmer
subcontractors.created_at.migration-nachunternehmer
subcontractors.email.migration-nachunternehmer
subcontractors.firma.migration-nachunternehmer
subcontractors.freistellung_bis.migration-nachunternehmer
subcontractors.gutschrift_verfahren.migration-nachunternehmer
subcontractors.haftpflicht_bis.migration-nachunternehmer
subcontractors.id.migration-nachunternehmer
subcontractors.is_active.migration-nachunternehmer
subcontractors.notizen.migration-nachunternehmer
subcontractors.phone.migration-nachunternehmer
subcontractors.preis_m2_demontage.migration-nachunternehmer
subcontractors.preis_m2_montage.migration-nachunternehmer
subcontractors.sicherheitseinbehalt_prozent.migration-nachunternehmer
subcontractors.steuernummer.migration-nachunternehmer
subcontractors.street.migration-nachunternehmer
subcontractors.stundensatz_regie.migration-nachunternehmer
subcontractors.unbedenklichkeit_bis.migration-nachunternehmer
subcontractors.updated_at.migration-nachunternehmer
subcontractors.ust_idnr.migration-nachunternehmer
subcontractors.zip.migration-nachunternehmer
subscriptions.cancel_at_period_end.phase-12-stripe-abo
subscriptions.company_name.phase-12-stripe-abo
subscriptions.created_at.phase-12-stripe-abo
subscriptions.current_period_end.phase-12-stripe-abo
subscriptions.customer_email.phase-12-stripe-abo
subscriptions.id.phase-12-stripe-abo
subscriptions.status.phase-12-stripe-abo
subscriptions.stripe_customer_id.phase-12-stripe-abo
subscriptions.stripe_price_id.phase-12-stripe-abo
subscriptions.stripe_subscription_id.phase-12-stripe-abo
subscriptions.tenant_id.phase-12-stripe-abo
subscriptions.trial_end.phase-12-stripe-abo
subscriptions.updated_at.phase-12-stripe-abo
taeglicher_einsatz.created_at.phase-54-wochenplanung
taeglicher_einsatz.einsatz_datum.phase-54-wochenplanung
taeglicher_einsatz.employee_id.phase-54-wochenplanung
taeglicher_einsatz.id.phase-54-wochenplanung
taeglicher_einsatz.notiz.phase-54-wochenplanung
taeglicher_einsatz.project_id.phase-54-wochenplanung
taeglicher_einsatz.updated_at.phase-54-wochenplanung
tenants.admin_email.phase-10-tenants
tenants.admin_name.phase-10-tenants
tenants.company_name.phase-10-tenants
tenants.created_at.phase-10-tenants
tenants.error_message.phase-10-tenants
tenants.id.phase-10-tenants
tenants.plan.phase-10-tenants
tenants.provision_log.phase-10-tenants
tenants.provision_step.phase-10-tenants
tenants.slug.phase-10-tenants
tenants.status.phase-10-tenants
tenants.subdomain.phase-10-tenants
tenants.supabase_anon_key.phase-10-tenants
tenants.supabase_project_ref.phase-10-tenants
tenants.supabase_service_role_key.phase-10-tenants
tenants.supabase_url.phase-10-tenants
tenants.updated_at.phase-10-tenants
tenants.vercel_project_id.phase-10-tenants
time_entries.break_minutes.kunden-schema
time_entries.created_at.kunden-schema
time_entries.created_by.kunden-schema
time_entries.employee_id.kunden-schema
time_entries.end_time.kunden-schema
time_entries.fahrzeit_minuten.phase-53-lohn-zusatzfelder
time_entries.hours.kunden-schema
time_entries.id.kunden-schema
time_entries.note.kunden-schema
time_entries.project_id.kunden-schema
time_entries.spesen_euro.phase-53-lohn-zusatzfelder
time_entries.start_time.kunden-schema
time_entries.tour_id.kunden-schema
time_entries.uebernachtung.phase-53-lohn-zusatzfelder
time_entries.updated_at.kunden-schema
time_entries.work_date.kunden-schema
tour_assignments.confirmed.kunden-schema
tour_assignments.confirmed_at.kunden-schema
tour_assignments.created_at.kunden-schema
tour_assignments.employee_id.kunden-schema
tour_assignments.id.kunden-schema
tour_assignments.role_in_tour.kunden-schema
tour_assignments.tour_id.kunden-schema
tour_plans.created_at.kunden-schema
tour_plans.created_by.kunden-schema
tour_plans.end_time.kunden-schema
tour_plans.id.kunden-schema
tour_plans.is_optimized.kunden-schema
tour_plans.optimization_notes.kunden-schema
tour_plans.planned_date.kunden-schema
tour_plans.project_id.kunden-schema
tour_plans.start_time.kunden-schema
tour_plans.status.kunden-schema
tour_plans.transport_order_id.kunden-schema
tour_plans.updated_at.kunden-schema
tour_plans.updated_by.kunden-schema
tour_plans.vehicle_id.kunden-schema
tour_stops.actual_arrival.kunden-schema
tour_stops.address.kunden-schema
tour_stops.created_at.kunden-schema
tour_stops.estimated_arrival.kunden-schema
tour_stops.id.kunden-schema
tour_stops.lat.kunden-schema
tour_stops.lng.kunden-schema
tour_stops.notes.kunden-schema
tour_stops.project_id.kunden-schema
tour_stops.status.kunden-schema
tour_stops.stop_order.kunden-schema
tour_stops.tour_id.kunden-schema
tour_stops.transport_order_id.kunden-schema
tours.completed_at.kunden-schema
tours.created_at.kunden-schema
tours.driver_id.kunden-schema
tours.estimated_duration_min.kunden-schema
tours.id.kunden-schema
tours.name.kunden-schema
tours.notes.kunden-schema
tours.planned_date.kunden-schema
tours.planned_start_time.kunden-schema
tours.route_data.kunden-schema
tours.route_optimized.kunden-schema
tours.status.kunden-schema
tours.total_distance_km.kunden-schema
tours.total_weight_kg.kunden-schema
tours.updated_at.kunden-schema
tours.vehicle_id.kunden-schema
transport_orders.completed_at.kunden-schema
transport_orders.created_at.kunden-schema
transport_orders.created_by.kunden-schema
transport_orders.driver_id.kunden-schema
transport_orders.empty_run_saved.kunden-schema
transport_orders.from_project_id.kunden-schema
transport_orders.id.kunden-schema
transport_orders.inventory_id.kunden-schema
transport_orders.is_optimized.kunden-schema
transport_orders.notes.kunden-schema
transport_orders.optimization_reason.kunden-schema
transport_orders.planned_date.kunden-schema
transport_orders.planned_time.kunden-schema
transport_orders.priority.kunden-schema
transport_orders.quantity.kunden-schema
transport_orders.status.kunden-schema
transport_orders.to_project_id.kunden-schema
transport_orders.updated_at.kunden-schema
transport_orders.updated_by.kunden-schema
transport_orders.vehicle_id.kunden-schema
vehicles.capacity_kg.kunden-schema
vehicles.created_at.kunden-schema
vehicles.current_location.kunden-schema
vehicles.fuel_type.kunden-schema
vehicles.id.kunden-schema
vehicles.is_active.kunden-schema
vehicles.last_gps_at.kunden-schema
vehicles.last_gps_lat.kunden-schema
vehicles.last_gps_lng.kunden-schema
vehicles.license_plate.kunden-schema
vehicles.name.kunden-schema
vehicles.notes.kunden-schema
vehicles.status.kunden-schema
vehicles.type.kunden-schema
vehicles.updated_at.kunden-schema
vehicles.volume_m3.kunden-schema$$
, E'\n') as zeile
  where zeile <> ''
),
actual_tables as (
  select table_name from information_schema.tables
  where table_schema = 'public' and table_type = 'BASE TABLE'
),
actual_cols as (
  select table_name, column_name from information_schema.columns
  where table_schema = 'public'
)
select quelle as migrationsdatei, tabelle,
       case when spalte is null then 'TABELLE FEHLT' else 'SPALTE FEHLT' end as was,
       spalte
from expected e
where (e.spalte is null and not exists (select 1 from actual_tables t where t.table_name = e.tabelle))
   or (e.spalte is not null and not exists (select 1 from actual_cols c where c.table_name = e.tabelle and c.column_name = e.spalte))
order by migrationsdatei, tabelle, spalte;

-- Ergebnis: 0 Zeilen = alles vollstaendig. Jede Zeile = fehlende
-- Migration/Nachhole-Spalte. Liste hierher schicken.
